Revert broken part of [6f653c5a2ba30008d62ab589ff5686df8a29ef72].
This was obviously untested as it breaks external ffmpeg build and only changes this code path.
xbmc/cores/dvdplayer/DVDDemuxers/DVDDemuxers.a(DVDDemuxFFmpeg.o): In function `DllAvFormat::av_read_frame_flush(AVFormatContext*):
/home/alexis/xbmc/lib/DllAvFormat.h:121: undefined reference to
`ff_read_frame_flush'

Even if it did not break, the change is wrong anyway.